In [60]:
import numpy as np
import copy

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.



In [233]:
def _det(a):
    m = len(a)
    n = len(a[0])
    if m == n:
        if m == 2:
            det=a[0][0]*a[1][1]-a[0][1]*a[1][0]
            return det
        
        else:
            if m != 2:
                a_1_j = a[0]
                a = a[1::]
                A = 0
                for a_i_j, a_i_j_value in enumerate(a_1_j):
                    
                    M = [row[:a_i_j:]+row[a_i_j+1::] for row in a]
                    det = _det(M)
                    A += (-1)**(a_i_j)*a_i_j_value*det
                return A
    else:
        print(f'Матрица не квадратная, определителя нет.')

In [234]:
a = [[4, 2, 3, 12], [0, 0, 1, 8], [0, 0, 9, 6], [0, 0, 0, 3]]
_a = copy.copy(a)

In [237]:
det = _det(_a)
print(det)

0


In [244]:
A = np.array(a)
print(A)
_detA = np.linalg.det(A)
print(_detA)

[[ 4  2  3 12]
 [ 0  0  1  8]
 [ 0  0  9  6]
 [ 0  0  0  3]]
0.0



1. Вычислить определитель:

a)

$$\begin{vmatrix} sinx & -cosx\\ cosx & sinx \end{vmatrix} = sinx^2 + cosx^2 = 1$$

б)

$$\begin{vmatrix} 4 & 2 & 3\\ 0 & 5 & 1\\ 0 & 0 & 9 \end{vmatrix} = 4\cdot5\cdot9 = 180$$

в)

$$\begin{vmatrix} 1 & 2 & 3\\ 4 & 5 & 6\\ 7 & 8 & 9 \end{vmatrix} = 1\cdot(5\cdot9-6\cdot8)-2\cdot(4\cdot9-6\cdot7)+3\cdot(4\cdot8-5\cdot7) = 0$$


2. Определитель матрицы $A$ равен $4$. Найти:

а) $det(A^{2}) = det(A)\cdot det(A) = det(A)^2 = 16$;

б) $det(A^{T}) = det(A) = 4$;

в) $det(2A) = 2det(A)$ зависит от размерности матрицы $A$. Определитель матрицы равен $2^n\cdot det(A)$, где $n$ - порядок матрицы $A$.

3. Доказать, что матрица

$$\begin{pmatrix} -2 & 7 & -3\\ 4 & -14 & 6\\ -3 & 7 & 13 \end{pmatrix}$$

вырожденная.


Матрица вырожденная, если ее определитель равен 0.
Найдем определитель матрицы
$$\begin{pmatrix} -2 & 7 & -3\\ 4 & -14 & 6\\ -3 & 7 & 13 \end{pmatrix} = 2\cdot(14\cdot13+7\cdot6)-7\cdot(4\cdot13+6\cdot3)-3\cdot(4\cdot7-14\cdot3) = 448-490+42=0
$$

4. Найти ранг матрицы:

а) $\begin{pmatrix} 1 & 2 & 3\\ 1 & 1 & 1\\ 2 & 3 & 4 \end{pmatrix}$ 

Определитель исходной матрицы равен $0$. Вычеркнем первую строку и первый столбец, получим минор второго порядка $\begin{vmatrix} 1 & 1 \\ 3 & 4\end{vmatrix}$, определитель которого не равен $0$, следовательно ранг матрицы равен $2$.

б) $\begin{pmatrix} 0 & 0 & 2 & 1\\ 0 & 0 & 2 & 2\\ 0 & 0 & 4 & 3\\ 2 & 3 & 5 & 6 \end{pmatrix}$ 

Определитель исходной матрицы равен $0$. Вычеркнем первую строку и первый столбец, получим минор третьего порядка $\begin{vmatrix} 0 & 2 & 2 \\ 0 & 4 & 3 \\ 3 & 5 & 6\end{vmatrix}$, определитель которого не равен $0$, следовательно ранг матрицы равен $3$. 