In [46]:
import numpy as np

1. Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

    $AB$  - нет, из-за несоответствия количества строк и столбцов
    $BA$  - нет, из-за несоответствия количества строк и столбцов

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

    $AB$  - да, итоговая матрица 2х3
    $BA$  - нет, из-за несоответствия количества строк и столбцов

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

    $AB$  - да, итоговая матрица 8х8
    $BA$  - да, итоговая матрица 3х3

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

    $AB$  - да, итоговая матрица 4х4
    $BA$  - да, итоговая матрица 4х4

2. Найти сумму и произведение матриц $A=\begin{pmatrix} 1 & -2\\ 3 & 0 \end{pmatrix}$ и $B=\begin{pmatrix} 4 & -1\\ 0 & 5 \end{pmatrix}.$

In [12]:
a = np.array([[1, -2],[3, 0]])
b = np.array([[4, -1],[0, 5]])

In [10]:
A_plus_B = np.array([[1+4, -2-1],[3+0,0+5]])
A_plus_B

array([[ 5, -3],
       [ 3,  5]])

In [13]:
a+b

array([[ 5, -3],
       [ 3,  5]])

In [11]:
A_multiply_B = np.array([[1*4+(-2)*0, 1*(-1)+(-2)*5],[3*4+0*0,3+(-1)+0*5]])
A_multiply_B

array([[  4, -11],
       [ 12,   2]])

In [14]:
a.dot(b)

array([[  4, -11],
       [ 12,  -3]])

3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix} 1 & 7\\ 3 & -6 \end{pmatrix}$, $B=\begin{pmatrix} 0 & 5\\ 2 & -1 \end{pmatrix}$, $C=\begin{pmatrix} 2 & -4\\ 1 & 1 \end{pmatrix}.$

In [17]:
a = np.array([[1,7],[3,-6]])
b = np.array([[0,5],[2,-1]])
c = np.array([[2,-4],[1,1]])
_3a = np.array([[1*3,7*3],[3*3,-6*3]])
_2b = np.array([[0*2,5*2],[2*2,-1*2]])
_4c = np.array([[2*4,-4*4],[1*4,1*4]])
res = np.array([[1*3-0*2+2*4,7*3-5*2+(-4)*4],[3*3-2*2+1*4,(-6)*3-(-1)*2+1*4]])
res

array([[ 11,  -5],
       [  9, -12]])

In [18]:
3*a-2*b+4*c

array([[ 11,  -5],
       [  9, -12]])

4. Дана матрица $A=\begin{pmatrix} 4 & 1\\ 5 & -2\\ 2 & 3 \end{pmatrix}$. Вычислить $AA^{T}$ и $A^{T}A$.



In [21]:
a = np.array([[4,1],[5,-2],[2,3]])
a_T = np.array([[4,5,2],[1,-2,3]])

In [27]:
A_AT = np.array([[4*4+1*1,4*5+1*(-2),4*2+1*3],[5*4+(-2)*1,5*5+(-2)*(-2),5*2+(-2)*3],[2*4+3*1,2*5+3*(-2),2*2+3*3]])
print(a.dot(a.T))
A_AT

[[17 18 11]
 [18 29  4]
 [11  4 13]]


array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [30]:
AT_A = np.array([[4*4+5*5+2*2,4*1+5*(-2)+2*3],[1*4+(-2)*5+3*2,1*1+(-2)*(-2)+3*3]])
print(a.T.dot(a))
AT_A

[[45  0]
 [ 0 14]]


array([[45,  0],
       [ 0, 14]])

5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [106]:
a = np.array([[4,1],[5,-2],[2,3]])
b = np.array([[3,6,1],[2,-7,8]])

In [107]:
a

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [108]:
b

array([[ 3,  6,  1],
       [ 2, -7,  8]])

In [110]:
a_m = len(a)
a_n = len(a[0])
b_n = len(b)
b_k = len(b[0])
c = []
if a_n == b_n:
    for a_index, a_value in enumerate(a):
        c_i = []
        for b_i_index, b_value in enumerate(a):
            c_i_j = 0
            for b_j_index, b_value in enumerate(b):
                a_i_j = a[a_index,b_j_index]
                b_i_j = b[b_j_index,b_i_index]
                c_i_j += a_i_j*b_i_j
            c_i.append(c_i_j)
        c.append(c_i)
    print(np.array(c))
else:
    print('Произведение матриц не определено')

[[ 14  17  12]
 [ 11  44 -11]
 [ 12  -9  26]]


In [112]:
print(a.dot(b))

[[ 14  17  12]
 [ 11  44 -11]
 [ 12  -9  26]]
